### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by reza3320** [EstebanMagallonPerez/touchPad#1]
**https://github.com/EstebanMagallonPerez/touchPad/commit/6e08b978cb5d07a2f3e21ec01c834438e79b94ac#r49788257**

there is an error for line 162 :(
I wrote the error in line162's comment section.

**Comment by reza3320** [comment]
What's Up? Is there any solution?

**Comment by EstebanMagallonPerez** [comment]
Newest commit changes LOGGER to print. Hopefully resolves the issue you were facing.
